apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
  template:
    metadata:
      labels:
        app: ratelimit
    spec:
      containers:
        - name: ratelimit-server
          image: marselester/travel-ratelimit:v1.0.0
          ports:
            - containerPort: 5000
